name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar la versión de .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Ajusta según la versión que estés utilizando

      # Paso 3: Restaurar los paquetes NuGet
      - name: Restore NuGet packages
        run: dotnet restore Sistema/SistemaEventos/SistemaEventos.sln

      # Paso 4: Configuración de SonarCloud
      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          entryPoint: sonar-scanner
          args: |
            -Dsonar.organization=your_organization
            -Dsonar.projectKey=your_project_key
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Establecer el token como variable de entorno

      # Paso 5: Ejecutar el análisis de SonarCloud
      - name: Run SonarCloud scanner
        run: sonar-scanner
